# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\layouts\mainW.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 901)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(52, 53, 65);\n"
"}\n"
"\n"
"QStackedWidget {\n"
"    background-color: rgb(52, 53, 65);\n"
"    gridline-color: black;\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-radius:12px;\n"
"}\n"
"\n"
"QPushButton[class=\"botoes1\"] {\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"    background-color: qlineargradient(\n"
"        spread: pad, \n"
"        x1: 0, y1: 1, \n"
"        x2: 0, y2: 0, \n"
"        stop: 0 #648ed1,\n"
"        stop: 0.35 #366096,   /* Azul escuro */\n"
"        stop: 1 #366096  /* Azul claro */\n"
"    );\n"
"}\n"
"\n"
"QPushButton:hover[class=\"botoes1\"] {\n"
"    color: rgb(9, 9, 9);\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"    border-style: outset;\n"
"    border-color: black;\n"
"    background-color: #8cff57;\n"
"}\n"
"\n"
"QPushButton[class=\"botoes2\"] {\n"
"    background-color: rgb(37, 38, 47);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover[class=\"botoes2\"] {\n"
"    background-color: rgb(82, 84, 103);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(92, 94, 115);\n"
"    color: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(74, 76, 93);\n"
"color: white;\n"
"border-radius:12px;\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(74, 76, 93);\n"
"color: white;\n"
"border-radius:12px;\n"
"}\n"
"\n"
"QComboBox{\n"
"    color: white;\n"
"background-color: rgb(92, 94, 115);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"[class=\"config\"]{\n"
"    background-color: rgb(92, 94, 115);\n"
"     border-width: 2px;\n"
"    border-style: outset;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 70, 1011, 821))
        self.stackedWidget.setBaseSize(QtCore.QSize(1011, 821))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(0, 70, 991, 151))
        self.label_5.setStyleSheet("font-size: 25px;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page)
        self.pagNotas = QtWidgets.QWidget()
        self.pagNotas.setObjectName("pagNotas")
        self.label_8 = QtWidgets.QLabel(self.pagNotas)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 991, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.btnNotatransformar = QtWidgets.QPushButton(self.pagNotas)
        self.btnNotatransformar.setEnabled(True)
        self.btnNotatransformar.setGeometry(QtCore.QRect(790, 700, 201, 41))
        self.btnNotatransformar.setStyleSheet("")
        self.btnNotatransformar.setObjectName("btnNotatransformar")
        self.btnNotaarq = QtWidgets.QPushButton(self.pagNotas)
        self.btnNotaarq.setGeometry(QtCore.QRect(790, 100, 201, 41))
        self.btnNotaarq.setObjectName("btnNotaarq")
        self.label_9 = QtWidgets.QLabel(self.pagNotas)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 761, 31))
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.pagNotas)
        self.label_10.setGeometry(QtCore.QRect(20, 220, 761, 31))
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btnNotalocal = QtWidgets.QPushButton(self.pagNotas)
        self.btnNotalocal.setGeometry(QtCore.QRect(790, 250, 201, 41))
        self.btnNotalocal.setObjectName("btnNotalocal")
        self.localNotas = QtWidgets.QLineEdit(self.pagNotas)
        self.localNotas.setGeometry(QtCore.QRect(20, 100, 761, 41))
        self.localNotas.setText("")
        self.localNotas.setObjectName("localNotas")
        self.txtinfoNota = QtWidgets.QTextEdit(self.pagNotas)
        self.txtinfoNota.setGeometry(QtCore.QRect(20, 310, 761, 491))
        self.txtinfoNota.setObjectName("txtinfoNota")
        self.btnAbrPastaNota = QtWidgets.QPushButton(self.pagNotas)
        self.btnAbrPastaNota.setGeometry(QtCore.QRect(790, 640, 201, 41))
        self.btnAbrPastaNota.setStyleSheet("")
        self.btnAbrPastaNota.setObjectName("btnAbrPastaNota")
        self.localNotasSalvar = QtWidgets.QLineEdit(self.pagNotas)
        self.localNotasSalvar.setGeometry(QtCore.QRect(20, 250, 761, 41))
        self.localNotasSalvar.setText("")
        self.localNotasSalvar.setObjectName("localNotasSalvar")
        self.label_11 = QtWidgets.QLabel(self.pagNotas)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 61, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.pagNotas)
        self.label_12.setGeometry(QtCore.QRect(190, 160, 61, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.btnCNPJ = QtWidgets.QPushButton(self.pagNotas)
        self.btnCNPJ.setGeometry(QtCore.QRect(790, 320, 201, 41))
        self.btnCNPJ.setObjectName("btnCNPJ")
        self.btn_exportar = QtWidgets.QPushButton(self.pagNotas)
        self.btn_exportar.setGeometry(QtCore.QRect(790, 380, 201, 41))
        self.btn_exportar.setStyleSheet("")
        self.btn_exportar.setObjectName("btn_exportar")
        self.txtmes = QtWidgets.QComboBox(self.pagNotas)
        self.txtmes.setGeometry(QtCore.QRect(70, 161, 121, 31))
        self.txtmes.setObjectName("txtmes")
        self.txtmes.addItem("")
        self.txtmes.setItemText(0, "")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtmes.addItem("")
        self.txtano = QtWidgets.QComboBox(self.pagNotas)
        self.txtano.setGeometry(QtCore.QRect(240, 160, 121, 31))
        self.txtano.setAutoFillBackground(False)
        self.txtano.setObjectName("txtano")
        self.txtano.addItem("")
        self.txtano.setItemText(0, "")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.txtano.addItem("")
        self.btnFATtransformar = QtWidgets.QPushButton(self.pagNotas)
        self.btnFATtransformar.setEnabled(True)
        self.btnFATtransformar.setGeometry(QtCore.QRect(790, 760, 201, 41))
        self.btnFATtransformar.setStyleSheet("")
        self.btnFATtransformar.setObjectName("btnFATtransformar")
        self.btn_importar = QtWidgets.QPushButton(self.pagNotas)
        self.btn_importar.setGeometry(QtCore.QRect(790, 440, 201, 41))
        self.btn_importar.setStyleSheet("")
        self.btn_importar.setObjectName("btn_importar")
        self.stackedWidget.addWidget(self.pagNotas)
        self.pagPRN = QtWidgets.QWidget()
        self.pagPRN.setObjectName("pagPRN")
        self.label_2 = QtWidgets.QLabel(self.pagPRN)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 991, 31))
        self.label_2.setStyleSheet("font-size: 25px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnPRNarq = QtWidgets.QPushButton(self.pagPRN)
        self.btnPRNarq.setGeometry(QtCore.QRect(790, 130, 201, 41))
        self.btnPRNarq.setStyleSheet("")
        self.btnPRNarq.setObjectName("btnPRNarq")
        self.textoPRNarq = QtWidgets.QLineEdit(self.pagPRN)
        self.textoPRNarq.setGeometry(QtCore.QRect(20, 100, 761, 41))
        self.textoPRNarq.setStyleSheet("")
        self.textoPRNarq.setObjectName("textoPRNarq")
        self.textoPRNlocal = QtWidgets.QLineEdit(self.pagPRN)
        self.textoPRNlocal.setGeometry(QtCore.QRect(20, 250, 761, 41))
        self.textoPRNlocal.setStyleSheet("")
        self.textoPRNlocal.setObjectName("textoPRNlocal")
        self.btnPRNlocal = QtWidgets.QPushButton(self.pagPRN)
        self.btnPRNlocal.setGeometry(QtCore.QRect(790, 250, 201, 41))
        self.btnPRNlocal.setStyleSheet("")
        self.btnPRNlocal.setObjectName("btnPRNlocal")
        self.label_6 = QtWidgets.QLabel(self.pagPRN)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 761, 31))
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.pagPRN)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 761, 31))
        self.label_7.setStyleSheet("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btnPRNtransformar = QtWidgets.QPushButton(self.pagPRN)
        self.btnPRNtransformar.setGeometry(QtCore.QRect(790, 760, 201, 41))
        self.btnPRNtransformar.setStyleSheet("")
        self.btnPRNtransformar.setObjectName("btnPRNtransformar")
        self.txtinfoPRN = QtWidgets.QTextEdit(self.pagPRN)
        self.txtinfoPRN.setGeometry(QtCore.QRect(20, 310, 761, 491))
        self.txtinfoPRN.setStyleSheet("")
        self.txtinfoPRN.setObjectName("txtinfoPRN")
        self.btnAbrPasta = QtWidgets.QPushButton(self.pagPRN)
        self.btnAbrPasta.setGeometry(QtCore.QRect(790, 700, 201, 41))
        self.btnAbrPasta.setStyleSheet("")
        self.btnAbrPasta.setObjectName("btnAbrPasta")
        self.btnPRNpasta = QtWidgets.QPushButton(self.pagPRN)
        self.btnPRNpasta.setGeometry(QtCore.QRect(790, 80, 201, 41))
        self.btnPRNpasta.setStyleSheet("")
        self.btnPRNpasta.setObjectName("btnPRNpasta")
        self.stackedWidget.addWidget(self.pagPRN)
        self.pagRazao = QtWidgets.QWidget()
        self.pagRazao.setObjectName("pagRazao")
        self.label_RAZAO = QtWidgets.QLabel(self.pagRazao)
        self.label_RAZAO.setGeometry(QtCore.QRect(10, 10, 991, 31))
        self.label_RAZAO.setStyleSheet("font-size: 25px;")
        self.label_RAZAO.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RAZAO.setObjectName("label_RAZAO")
        self.razao_arq = QtWidgets.QLineEdit(self.pagRazao)
        self.razao_arq.setGeometry(QtCore.QRect(20, 100, 761, 41))
        self.razao_arq.setStyleSheet("")
        self.razao_arq.setObjectName("razao_arq")
        self.btnAbrPastaRazao = QtWidgets.QPushButton(self.pagRazao)
        self.btnAbrPastaRazao.setGeometry(QtCore.QRect(790, 700, 201, 41))
        self.btnAbrPastaRazao.setStyleSheet("")
        self.btnAbrPastaRazao.setObjectName("btnAbrPastaRazao")
        self.btnRAZAOpasta = QtWidgets.QPushButton(self.pagRazao)
        self.btnRAZAOpasta.setGeometry(QtCore.QRect(790, 80, 201, 41))
        self.btnRAZAOpasta.setStyleSheet("")
        self.btnRAZAOpasta.setObjectName("btnRAZAOpasta")
        self.btnRAZAOtransformar = QtWidgets.QPushButton(self.pagRazao)
        self.btnRAZAOtransformar.setGeometry(QtCore.QRect(790, 760, 201, 41))
        self.btnRAZAOtransformar.setStyleSheet("")
        self.btnRAZAOtransformar.setObjectName("btnRAZAOtransformar")
        self.txtinfoRAZAO = QtWidgets.QTextEdit(self.pagRazao)
        self.txtinfoRAZAO.setGeometry(QtCore.QRect(20, 310, 761, 491))
        self.txtinfoRAZAO.setStyleSheet("")
        self.txtinfoRAZAO.setObjectName("txtinfoRAZAO")
        self.btnRAZAOarq = QtWidgets.QPushButton(self.pagRazao)
        self.btnRAZAOarq.setGeometry(QtCore.QRect(790, 130, 201, 41))
        self.btnRAZAOarq.setStyleSheet("")
        self.btnRAZAOarq.setObjectName("btnRAZAOarq")
        self.label_22 = QtWidgets.QLabel(self.pagRazao)
        self.label_22.setGeometry(QtCore.QRect(10, 220, 771, 31))
        self.label_22.setStyleSheet("")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_razao2 = QtWidgets.QLabel(self.pagRazao)
        self.label_razao2.setGeometry(QtCore.QRect(10, 70, 771, 31))
        self.label_razao2.setStyleSheet("")
        self.label_razao2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_razao2.setObjectName("label_razao2")
        self.razao_local = QtWidgets.QLineEdit(self.pagRazao)
        self.razao_local.setGeometry(QtCore.QRect(20, 250, 761, 41))
        self.razao_local.setStyleSheet("")
        self.razao_local.setObjectName("razao_local")
        self.btnRAZAOlocal = QtWidgets.QPushButton(self.pagRazao)
        self.btnRAZAOlocal.setGeometry(QtCore.QRect(790, 250, 201, 41))
        self.btnRAZAOlocal.setStyleSheet("")
        self.btnRAZAOlocal.setObjectName("btnRAZAOlocal")
        self.rb_razao = QtWidgets.QRadioButton(self.pagRazao)
        self.rb_razao.setGeometry(QtCore.QRect(650, 150, 121, 21))
        self.rb_razao.setObjectName("rb_razao")
        self.stackedWidget.addWidget(self.pagRazao)
        self.pagRateio = QtWidgets.QWidget()
        self.pagRateio.setObjectName("pagRateio")
        self.btncss = QtWidgets.QPushButton(self.pagRateio)
        self.btncss.setGeometry(QtCore.QRect(30, 30, 201, 41))
        self.btncss.setStyleSheet("")
        self.btncss.setObjectName("btncss")
        self.stackedWidget.addWidget(self.pagRateio)
        self.btnNotas = QtWidgets.QPushButton(self.centralwidget)
        self.btnNotas.setGeometry(QtCore.QRect(10, 10, 151, 51))
        self.btnNotas.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:1, \n"
"        x2:0, y2:0, \n"
"        stop:0 #648ed1,\n"
"        stop:0.35 #366096,   /* Azul escuro (rgb(7, 0, 235)) */\n"
"        stop:1 #366096  /* Azul claro (rgb(0, 255, 255)) */\n"
"    );\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(9, 9, 9);\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: #8cff57;\n"
"}")
        self.btnNotas.setObjectName("btnNotas")
        self.btnPRN = QtWidgets.QPushButton(self.centralwidget)
        self.btnPRN.setGeometry(QtCore.QRect(170, 10, 151, 51))
        self.btnPRN.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:1, \n"
"        x2:0, y2:0, \n"
"        stop:0 #648ed1,\n"
"        stop:0.35 #366096,   /* Azul escuro (rgb(7, 0, 235)) */\n"
"        stop:1 #366096  /* Azul claro (rgb(0, 255, 255)) */\n"
"    );\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(9, 9, 9);\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: #8cff57;\n"
"}")
        self.btnPRN.setObjectName("btnPRN")
        self.btnRazao = QtWidgets.QPushButton(self.centralwidget)
        self.btnRazao.setEnabled(True)
        self.btnRazao.setGeometry(QtCore.QRect(330, 10, 151, 51))
        self.btnRazao.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:1, \n"
"        x2:0, y2:0, \n"
"        stop:0 #648ed1,\n"
"        stop:0.35 #366096,   /* Azul escuro (rgb(7, 0, 235)) */\n"
"        stop:1 #366096  /* Azul claro (rgb(0, 255, 255)) */\n"
"    );\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(9, 9, 9);\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: #8cff57;\n"
"}")
        self.btnRazao.setObjectName("btnRazao")
        self.btnRateio = QtWidgets.QPushButton(self.centralwidget)
        self.btnRateio.setEnabled(False)
        self.btnRateio.setGeometry(QtCore.QRect(490, 10, 151, 51))
        self.btnRateio.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:1, \n"
"        x2:0, y2:0, \n"
"        stop:0 #648ed1,\n"
"        stop:0.35 #366096,   /* Azul escuro (rgb(7, 0, 235)) */\n"
"        stop:1 #366096  /* Azul claro (rgb(0, 255, 255)) */\n"
"    );\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: #8cff57;\n"
"}")
        self.btnRateio.setText("")
        self.btnRateio.setObjectName("btnRateio")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(770, 10, 151, 51))
        self.btnVoltar.setStyleSheet("QPushButton{\n"
"color: rgb(9, 9, 9);\n"
"border-radius: 15px;\n"
"border-width:2px;\n"
"background-color: #8cff57;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(9, 9, 9);\n"
"border-radius: 15px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: #8cff57;\n"
"}")
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnconfig = QtWidgets.QPushButton(self.centralwidget)
        self.btnconfig.setEnabled(True)
        self.btnconfig.setGeometry(QtCore.QRect(930, 10, 91, 51))
        self.btnconfig.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:1, \n"
"        x2:0, y2:0, \n"
"        stop:0 #648ed1,\n"
"        stop:0.35 #366096,   /* Azul escuro (rgb(7, 0, 235)) */\n"
"        stop:1 #366096  /* Azul claro (rgb(0, 255, 255)) */\n"
"    );\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 10px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: #8cff57;\n"
"}")
        self.btnconfig.setObjectName("btnconfig")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XY-auto"))
        self.label_5.setText(_translate("MainWindow", "PROGRAMA DE AUTOMACAO V1.6.3"))
        self.label_8.setText(_translate("MainWindow", "NOTAS+FATURAMENTO"))
        self.btnNotatransformar.setText(_translate("MainWindow", "GERAR NOTAS"))
        self.btnNotatransformar.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btnNotaarq.setText(_translate("MainWindow", "SELECIONAR PASTA"))
        self.btnNotaarq.setProperty("class", _translate("MainWindow", "botoes2"))
        self.label_9.setText(_translate("MainWindow", "SELECIONAR DOS ARQUIVOS"))
        self.label_10.setText(_translate("MainWindow", "LOCAL PARA SALVAR"))
        self.btnNotalocal.setText(_translate("MainWindow", "SELECIONAR LOCAL"))
        self.btnNotalocal.setProperty("class", _translate("MainWindow", "botoes2"))
        self.txtinfoNota.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.btnAbrPastaNota.setText(_translate("MainWindow", "ABRIR PASTA"))
        self.btnAbrPastaNota.setProperty("class", _translate("MainWindow", "botoes1"))
        self.label_11.setText(_translate("MainWindow", "MÊS:"))
        self.label_12.setText(_translate("MainWindow", "ANO:"))
        self.btnCNPJ.setText(_translate("MainWindow", "PESQUISAR CNPJS"))
        self.btnCNPJ.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btn_exportar.setText(_translate("MainWindow", "EXPORTAR BANCO"))
        self.btn_exportar.setProperty("class", _translate("MainWindow", "botoes1"))
        self.txtmes.setItemText(1, _translate("MainWindow", "01"))
        self.txtmes.setItemText(2, _translate("MainWindow", "02"))
        self.txtmes.setItemText(3, _translate("MainWindow", "03"))
        self.txtmes.setItemText(4, _translate("MainWindow", "04"))
        self.txtmes.setItemText(5, _translate("MainWindow", "05"))
        self.txtmes.setItemText(6, _translate("MainWindow", "06"))
        self.txtmes.setItemText(7, _translate("MainWindow", "07"))
        self.txtmes.setItemText(8, _translate("MainWindow", "08"))
        self.txtmes.setItemText(9, _translate("MainWindow", "09"))
        self.txtmes.setItemText(10, _translate("MainWindow", "10"))
        self.txtmes.setItemText(11, _translate("MainWindow", "11"))
        self.txtmes.setItemText(12, _translate("MainWindow", "12"))
        self.txtano.setItemText(1, _translate("MainWindow", "2018"))
        self.txtano.setItemText(2, _translate("MainWindow", "2019"))
        self.txtano.setItemText(3, _translate("MainWindow", "2020"))
        self.txtano.setItemText(4, _translate("MainWindow", "2021"))
        self.txtano.setItemText(5, _translate("MainWindow", "2022"))
        self.txtano.setItemText(6, _translate("MainWindow", "2023"))
        self.txtano.setItemText(7, _translate("MainWindow", "2024"))
        self.txtano.setItemText(8, _translate("MainWindow", "2025"))
        self.txtano.setItemText(9, _translate("MainWindow", "2026"))
        self.txtano.setItemText(10, _translate("MainWindow", "2027"))
        self.txtano.setItemText(11, _translate("MainWindow", "2028"))
        self.txtano.setItemText(12, _translate("MainWindow", "2029"))
        self.txtano.setItemText(13, _translate("MainWindow", "2030"))
        self.btnFATtransformar.setText(_translate("MainWindow", "GERAR FATURAMENTO"))
        self.btnFATtransformar.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btn_importar.setText(_translate("MainWindow", "IMPORTAR BANCO"))
        self.btn_importar.setProperty("class", _translate("MainWindow", "botoes1"))
        self.label_2.setText(_translate("MainWindow", "Transformar PRN"))
        self.btnPRNarq.setText(_translate("MainWindow", "SELECIONAR ARQ"))
        self.btnPRNarq.setProperty("class", _translate("MainWindow", "botoes2"))
        self.btnPRNlocal.setText(_translate("MainWindow", "SELECIONAR LOCAL"))
        self.btnPRNlocal.setProperty("teste", _translate("MainWindow", "kk"))
        self.btnPRNlocal.setProperty("class", _translate("MainWindow", "botoes2"))
        self.label_6.setText(_translate("MainWindow", "LOCAL PARA SALVAR"))
        self.label_7.setText(_translate("MainWindow", "SELECIONAR ARQUIVO/PASTA"))
        self.btnPRNtransformar.setText(_translate("MainWindow", "TRANSFORMAR"))
        self.btnPRNtransformar.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btnAbrPasta.setText(_translate("MainWindow", "ABRIR PASTA"))
        self.btnAbrPasta.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btnPRNpasta.setText(_translate("MainWindow", "SELECIONAR PASTA"))
        self.btnPRNpasta.setProperty("class", _translate("MainWindow", "botoes2"))
        self.label_RAZAO.setText(_translate("MainWindow", "Transformar RAZAO"))
        self.btnAbrPastaRazao.setText(_translate("MainWindow", "ABRIR PASTA"))
        self.btnAbrPastaRazao.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btnRAZAOpasta.setText(_translate("MainWindow", "SELECIONAR PASTA"))
        self.btnRAZAOpasta.setProperty("class", _translate("MainWindow", "botoes2"))
        self.btnRAZAOtransformar.setText(_translate("MainWindow", "TRANSFORMAR"))
        self.btnRAZAOtransformar.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btnRAZAOarq.setText(_translate("MainWindow", "SELECIONAR ARQ"))
        self.btnRAZAOarq.setProperty("class", _translate("MainWindow", "botoes2"))
        self.label_22.setText(_translate("MainWindow", "LOCAL PARA SALVAR"))
        self.label_razao2.setText(_translate("MainWindow", "SELECIONAR ARQUIVO/PASTA"))
        self.btnRAZAOlocal.setText(_translate("MainWindow", "SELECIONAR LOCAL"))
        self.btnRAZAOlocal.setProperty("teste", _translate("MainWindow", "kk"))
        self.btnRAZAOlocal.setProperty("class", _translate("MainWindow", "botoes2"))
        self.rb_razao.setText(_translate("MainWindow", "RESUMO"))
        self.btncss.setText(_translate("MainWindow", "EXPORTA CSS"))
        self.btncss.setProperty("class", _translate("MainWindow", "botoes1"))
        self.btnNotas.setText(_translate("MainWindow", "NOTAS+FAT"))
        self.btnPRN.setText(_translate("MainWindow", "PRN"))
        self.btnRazao.setText(_translate("MainWindow", "RAZAO"))
        self.btnVoltar.setText(_translate("MainWindow", "VOLTAR"))
        self.btnconfig.setText(_translate("MainWindow", "CONFIG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
